---
# tasks file for acs

- name: Create {{ acs_user }} user account
  user:
    name: "{{ acs_user }}"
    shell: /bin/bash

- name: Create {{ acs_install_folder }}
  file:
    path: "{{ acs_install_folder }}"
    state: directory
    owner: "{{ acs_user }}"
    group: "{{ acs_user }}"
    mode: 0755
  register: createdInstallFolder

- name: get content of {{ acs_install_folder }}
  command: ls {{ acs_install_folder }}
  register: acs_install_folder_contents
  changed_when: false

- name: download ACS from Nexus
  include_tasks: download.yml
  when: not nexus_user == None and not nexus_password == None and not acs_install_folder_contents.stdout
